name: MCPublish
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build
      - name: 'MC Publish'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: mc1.19.4-0.1.9
          github-generate-changelog: true
          github-token: ${{ secrets.GITHUB_TOKEN }}